apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: devices.test.com
spec:
  group: test.com
  names:
    kind: Device
    plural: devices
    singular: device
  scope: Namespaced
  version: v1

