apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devices.test.com
spec:
  group: test.com
  names:
    kind: Device
    plural: devices
    singular: device
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                power:
                  type: boolean
                workloads:
                  type: object



# ---

#apiVersion: apiextensions.k8s.io/v1beta1
#kind: CustomResourceDefinition
#metadata:
#  name: devicekeepers.test.com
#spec:
#  group: test.com
#  names:
#    kind: Devicekeep
#    plural: devicekeeps
#    singular: device
#  scope: Namespaced
#  version: v1

